name: sustainable_people CI/CD

on:
  pull_request_target:
    branches:
      - main
    types:
      - closed

jobs:
  build-deploy:   # jobname
    if: github.event.pull_request.merged == true    # ÏàòÌñâ Ï°∞Í±¥
    runs-on: ubuntu-latest
    steps:
      - name: ‚úÖ Checkout Repository
        uses: actions/checkout@v3

      - name: üêç Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: üîë Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: ‚ôªÔ∏è Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: üèóÔ∏è Build and Push Docker images
        uses: docker/build-push-action@v2
        with:
          context: ./vogue_me
          file: ./vogue_me/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKER_IMAGENAME }}:latest

      - name: üöÄ Deploy Beanstalk
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ secrets.AWS_EB_APPLICATION_NAME }}
          environment_name: ${{ secrets.AWS_EB_ENVIRONMENT_NAME }}
          region: ap-northeast-2
          version_label: "app-${{ github.sha }}-run${{ github.run_number }}"
          deployment_package: Dockerrun.aws.json